# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r:
- oldrel
- release
- devel

matrix:
  include:
    - os: linux
      before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y libboost-regex-dev
    - os: osx
      before_install:
        - brew install boost
      latex: false

