# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      r: release
    - os: linux
      r: oldrel
    - os: linux
      r: devel
    - os: osx
      r: release
      before_install:
        - brew upgrade boost
      latex: false

warnings_are_errors: false

addons:
  apt:
    packages:
      - libboost-regex-dev
