# DO NOT CHANGE the "init" and "install" sections below

# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - cd %BOOST_ROOT%
  - call bootstrap.bat mingw
  - .\b2 toolset=msvc-14.0 variant=release --with-regex --stagedir=stage\lib64 address-model=64 --build-type=complete --threading=multi
  - .\b2 toolset=msvc-14.0 variant=release --with-regex --stagedir=stage\lib32 address-model=32 --build-type=complete --threading=multi --reconfigure
  - set PATH=%BOOST_ROOT%;%PATH%
  - cd %APPVEYOR_BUILD_FOLDER%

cache:
  - C:\RLibrary

# Adapt as necessary starting from here

environment:
  global:
    CRAN: http://cloud.r-project.org/
    WARNINGS_ARE_ERRORS:
    USE_RTOOLS: true
    GCC_PATH: mingw_64
    BOOST_ROOT: C:\Libraries\boost_1_59_0
    BOOST_LIBRARYDIR: C:\Libraries\boost_1_59_0\lib
    BOOST_INCLUDEDIR: C:\Libraries\boost_1_59_0\include\boost

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - 7z a failure.zip *.Rcheck\*
  - appveyor PushArtifact failure.zip

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
